name: DeACoudre
version: 2.0.4
main: fr.naruse.dac.main.DACPlugin
author: Naruse
softdepend:
  - DBAPI
  - HolographicDisplays
  - Vault
  - SecondThreadAPI
  - NaruseAPI
  - DecentHolograms
commands:
  dac: